version: '3'

services:
  pinuswap-dex:
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
